import { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { FileText, Download } from 'lucide-react';
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, PieChart, Pie, Cell } from 'recharts';
import { adminAPI } from '../../services/api';
import { formatDateTime, formatNumber } from '../../utils/helpers';
import { exportSystemReportCsv, exportSystemReportPdf } from '../../utils/adminSystemReportExport';
import { logUserActivity } from '../../utils/auditClient';
import DataTable from '../../components/DataTable';
import PageHeader, { StatusBadge } from '../../components/PageHeader';
import ChartCard from '../../components/ChartCard';
import StatCard from '../../components/StatCard';
import AdminPage from '../../components/AdminPage';
import { Activity, FolderKanban, MessageSquare, ScrollText } from 'lucide-react';

const COLORS = ['#E67E22', '#2C3E50', '#27AE60'];

function defaultRange() {
  const end = new Date();
  const start = new Date();
  start.setDate(start.getDate() - 30);
  return {
    startDate: start.toISOString().slice(0, 10),
    endDate: end.toISOString().slice(0, 10),
  };
}

export default function AdminReports() {
  const [range, setRange] = useState(defaultRange);

  const { data: perf, isLoading: loadingPerf } = useQuery({
    queryKey: ['admin-system-reports', range],
    queryFn: () => adminAPI.getSystemReports(range),
  });

  const { data: reportsData, isLoading } = useQuery({
    queryKey: ['admin-reports-list'],
    queryFn: () => adminAPI.getReports(),
  });

  const summary = perf?.summary || {};
  const activityChart = perf?.activityChart || [];
  const projectsChart = perf?.projectsChart || [];
  const usersByRole = perf?.usersByRole || [];
  const messagesChart = perf?.messagesChart || [];
  const workLogsChart = perf?.workLogsChart || [];
  const loginActivityChart = perf?.loginActivityChart || [];
  const issuesByStatus = perf?.issuesByStatus || [];
  const reports = reportsData?.reports || [];

  const exportPayload = useMemo(
    () => perf || { range, summary: {}, activityChart: [], projectsChart: [] },
    [perf, range],
  );

  const columns = [
    { header: 'Title', accessor: 'title', sortable: true },
    { header: 'Type', accessor: 'report_type', render: (row) => <StatusBadge status={row.report_type || row.reportType || 'draft'} /> },
    { header: 'Project', accessor: 'project_name', render: (r) => r.project_name || r.projectName || '—' },
    { header: 'Generated By', accessor: 'created_by_name', render: (r) => r.created_by_name || '—' },
    { header: 'Date', accessor: 'created_at', render: (row) => formatDateTime(row.created_at || row.createdAt) },
  ];

  return (
    <AdminPage>
      <PageHeader
        title="System Reports"
        subtitle="Platform performance with date range, charts, and stored PM/contractor reports"
      />

      <div className="card flex flex-wrap gap-4 items-end">
        <div>
          <label className="label">From</label>
          <input type="date" className="input" value={range.startDate} onChange={(e) => setRange((r) => ({ ...r, startDate: e.target.value }))} />
        </div>
        <div>
          <label className="label">To</label>
          <input type="date" className="input" value={range.endDate} onChange={(e) => setRange((r) => ({ ...r, endDate: e.target.value }))} />
        </div>
        <button type="button" className="btn-outline inline-flex items-center gap-2" onClick={() => { logUserActivity('DOWNLOAD_EXPORT_PDF', { scope: 'system-reports', ...range }); exportSystemReportPdf(exportPayload); }}>
          <Download className="h-4 w-4" /> PDF
        </button>
        <button type="button" className="btn-primary inline-flex items-center gap-2" onClick={() => { logUserActivity('DOWNLOAD_EXPORT_CSV', { scope: 'system-reports', ...range }); exportSystemReportCsv(exportPayload); }}>
          <Download className="h-4 w-4" /> CSV
        </button>
      </div>

      {loadingPerf ? (
        <div className="h-32 animate-pulse bg-steel-50 rounded-2xl" />
      ) : (
        <>
          <div className="grid w-full gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <StatCard title="Audit events" value={formatNumber(summary.auditEvents)} icon={ScrollText} />
            <StatCard title="New projects" value={formatNumber(summary.newProjects)} icon={FolderKanban} />
            <StatCard title="Messages" value={formatNumber(summary.messagesSent)} icon={MessageSquare} />
            <StatCard title="Work logs" value={formatNumber(summary.workLogs)} icon={Activity} />
          </div>

          <div className="grid w-full gap-6 lg:grid-cols-2">
            <ChartCard title="Audit activity" subtitle="Events per day">
              {activityChart.length ? (
                <LineChart data={activityChart}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#ECF0F1" />
                  <XAxis dataKey="day" tick={{ fontSize: 10 }} />
                  <YAxis allowDecimals={false} tick={{ fontSize: 11 }} />
                  <Tooltip />
                  <Line type="monotone" dataKey="events" stroke="#E67E22" strokeWidth={2} dot />
                </LineChart>
              ) : (
                <p className="text-sm text-concrete py-12 text-center">No events in range</p>
              )}
            </ChartCard>
            <ChartCard title="New projects" subtitle="Created per day">
              {projectsChart.length ? (
                <BarChart data={projectsChart}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#ECF0F1" />
                  <XAxis dataKey="day" tick={{ fontSize: 10 }} />
                  <YAxis allowDecimals={false} tick={{ fontSize: 11 }} />
                  <Tooltip />
                  <Bar dataKey="projects" fill="#2C3E50" radius={[4, 4, 0, 0]} />
                </BarChart>
              ) : (
                <p className="text-sm text-concrete py-12 text-center">No projects in range</p>
              )}
            </ChartCard>
          </div>

          <div className="grid w-full gap-6 lg:grid-cols-2 xl:grid-cols-3">
            <ChartCard title="Users by role" subtitle="Current totals">
              {usersByRole.length ? (
                <PieChart>
                  <Pie data={usersByRole} dataKey="count" nameKey="name" cx="50%" cy="50%" outerRadius={90} label>
                    {usersByRole.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
                  </Pie>
                  <Tooltip />
                </PieChart>
              ) : (
                <p className="text-sm text-concrete py-12 text-center">No user data</p>
              )}
            </ChartCard>
            <ChartCard title="Messages sent" subtitle="Per day in range">
                {messagesChart.length ? (
                  <BarChart data={messagesChart}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#ECF0F1" />
                    <XAxis dataKey="day" tick={{ fontSize: 9 }} />
                    <YAxis allowDecimals={false} tick={{ fontSize: 11 }} />
                    <Tooltip />
                    <Bar dataKey="messages" fill="#3498DB" radius={[4, 4, 0, 0]} />
                  </BarChart>
                ) : (
                  <p className="text-sm text-concrete py-12 text-center">No messages in range</p>
                )}
              </ChartCard>
              <ChartCard title="Work logs" subtitle="Daily field logs">
                {workLogsChart.length ? (
                  <LineChart data={workLogsChart}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#ECF0F1" />
                    <XAxis dataKey="day" tick={{ fontSize: 9 }} />
                    <YAxis allowDecimals={false} tick={{ fontSize: 11 }} />
                    <Tooltip />
                    <Line type="monotone" dataKey="logs" stroke="#27AE60" strokeWidth={2} dot />
                  </LineChart>
                ) : (
                  <p className="text-sm text-concrete py-12 text-center">No work logs in range</p>
                )}
              </ChartCard>
              <ChartCard title="User sign-in activity" subtitle="Login & logout events">
                {loginActivityChart.length ? (
                  <BarChart data={loginActivityChart}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#ECF0F1" />
                    <XAxis dataKey="day" tick={{ fontSize: 9 }} />
                    <YAxis allowDecimals={false} tick={{ fontSize: 11 }} />
                    <Tooltip />
                    <Bar dataKey="logins" fill="#9B59B6" radius={[4, 4, 0, 0]} />
                  </BarChart>
                ) : (
                  <p className="text-sm text-concrete py-12 text-center">No login activity in range</p>
                )}
              </ChartCard>
              <ChartCard title="Issues by status" subtitle="Platform-wide">
                {issuesByStatus.length ? (
                  <PieChart>
                    <Pie data={issuesByStatus} dataKey="count" nameKey="name" cx="50%" cy="50%" outerRadius={80} label>
                      {issuesByStatus.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                ) : (
                  <p className="text-sm text-concrete py-12 text-center">No issues recorded</p>
                )}
              </ChartCard>
              <div className="card flex flex-col justify-center gap-2 text-sm text-concrete">
                <p><strong className="text-steel">{formatNumber(summary.activeUsers)}</strong> active users</p>
                <p><strong className="text-steel">{formatNumber(summary.activeProjects)}</strong> in-progress projects</p>
                <p className="text-xs">Range: {perf?.range?.startDate} → {perf?.range?.endDate}</p>
              </div>
            </div>
        </>
      )}

      <div>
        <h3 className="font-semibold text-steel mb-3 flex items-center gap-2">
          <FileText className="h-4 w-4 text-primary" /> Stored reports ({reports.length})
        </h3>
        <DataTable columns={columns} data={reports} loading={isLoading} emptyMessage="No reports generated yet" />
      </div>
    </AdminPage>
  );
}
